name: Convert markdown to HTML and deploy to pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - run: mv template site
      - run: cargo run

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
      - name: Deploy pages
        uses: actions/deploy-pages@v4
